server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/paolonttdata/proyecto1
          searchPaths: config-data
          username: paolonttdata
          password: 2823eli
          default-label: "main"
  security:
    user:
      name: nttdata
      password: 2823eli. 

