# Docs for the Azure Web Apps Deploy action: https://github.com/paolonttdata/proyecto1
# More GitHub Actions for Azure: https://dev.azure.com/paolonttdata/_git/bootcamp

name: Build and deploy JAR app to Azure Web App - bootcamp-proyecto

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java version 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Build with Maven
        run: mvn -f ./proyecto/pom.xml clean install -Dmaven.test.skip=true
      - name: Upload artifact for deployment job
        with:
          name: java-app
          path: '${{ github.workspace }}/proyecto/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: bootcamp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bootcamp-app-proyecto'
          slot-name: 'main'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_547DA7121F764F6AB61FF3ADE539C81B }}
          package: '*.jar'
