# Docs for the Azure Web Apps Deploy action: https://github.com/paolonttdata/proyecto1
# More GitHub Actions for Azure: https://dev.azure.com/paolonttdata/_git/bootcamp

name: Build and deploy JAR app to Azure Web App - proyecto-eureka-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build with Maven
        run: mvn -f ./eureka-server/pom.xml clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/eureka-serverproject/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
